config/routes.rb
Rails.application.routes.draw do
  root "brands#index"

  resources :brands do
  end

  resources :products do
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  has_many :products, dependent: :destroy
  validates :name, presence: true,
                    length: { maximum: 20 }
  validates :headquarters, presence: true,
                    length: { maximum: 20 }
  validates :phone, presence: true,
                    length: { minimum: 11 , maximum: 20}
  validates :phone, numericality: { only_integer: true }
end

app/models/product.rb
  class Product < ApplicationRecord

  

  belongs_to :brand
  validates :name, presence: true,
                    length: { maximum: 20 }
  validates :color, presence: true,
                    length: { maximum: 20 }
  validates :price, presence: true,
                    length: { minimum: 1 , maximum: 7}
  validates :price, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
      @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to brands_path
    else
        render 'new'
    end
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to brands_path
    else
      render 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    redirect_to brands_path
  end

  private
    def brand_params
      params.require(:brand).permit(:name, :headquarters, :phone)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
      @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @brand = Product.find(params[:id]).brand_id
    @product = Product.find(params[:id])
  end


    def create
      @product = Product.create(product_params)
      if @product.save
          redirect_to products_path()
      else
          render 'new'
      end
    end

  def update
    @product = Product.find(params[:id])
    @brand = @product.brand_id

    if @product.update(product_params)
      redirect_to brands_path(@brand)
    else
      render 'edit'
    end
  end

  def destroy

   @brand = Product.find(params[:id]).brand_id
   @product = Product.find(params[:id])
   @product.destroy
   redirect_to brand_path(@brand)
 end

  private
    def product_params
      params.require(:product).permit(:name, :color, :price, :brand_id)
    end
end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wellcome_helper.rb
module WellcomeHelper
end

app/views/brands/_form.html.erb
<%= form_with model: @brand, local: true do |form| %>


      <% if @brand.errors.any? %>

        <div id="error_explanation">
            <div class="form-group alert alert-danger">
          <h2>
            <%= pluralize(@brand.errors.count, "Hata") %> yakalandı:
          </h2>

          <ul>
            <% @brand.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
        </div>
      <% end %>
<div class="form_body">
        <div class="form-group">
          <%= form.label :name,class:"col-form-label col-form-label-lg" %><br/>
          <%= form.text_field :name, class:"form-control form-control-lg" %>
        </div>
        <div class="form-group">
          <%= form.label :headquarters ,class:"col-form-label col-form-label-lg" %><br/>
          <%= form.text_field :headquarters , class:"form-control form-control-lg" %>
        </div>
        <div class="form-group">
          <%= form.label :phone ,class:"col-form-label col-form-label-lg" %><br/>
          <%= form.text_field :phone , class:"form-control form-control-lg" %>
        </div>

       <div class="form-group">
          <%= form.submit  %><br/>
       </div>
</div>

      <% end %>

app/views/brands/edit.html.erb
<div class="container">
  <h3>Edit Brand</h3>
</div>
<%= render 'form' %>

app/views/brands/index.html.erb
<div class="col-lg-12">


<div class="card" style="width: 100%;">

  <div class="card-body">
    <h5 class="card-title">Brands List</h5>
      <p class="card-text"><%= link_to 'New Brand', new_brand_path,class:"page_new_button" %></p>
  </div>


</div>
<!-- <h3>Brands List</h3> -->

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Headquarters</th>
      <th scope="col">Phone</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  <% @brands.each do |brand| %>
    <tr>
      <td><%= brand.name %></td>
      <td><%= brand.headquarters %></td>
      <td><%= brand.phone %></td>
      <td><%= link_to 'Show', brand_path(brand) %></td>
      <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
      <td><%= link_to 'Delete', brand_path(brand),
              method: :delete,
              data: { confirm: 'Emin misin?' } %></td>
    </tr>
    </tbody>
  <% end %>
</table>
</div>

app/views/brands/new.html.erb
<div class="col-lg-12 col-md-12">
    <h3 class="page_title">New Brand</h3>
    <%= render 'form' %>
</div>

app/views/brands/show.html.erb
<div class="container-fluid">
<div class="card" style="width: 100%;">

  <div class="card-body">
    <h5 class="card-title"><%= @brand.name.upcase %></h5>
    <p class="card-text">products</p>
  </div>


</div>
</div>



<%= render 'products/product' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ETicaret</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <div id="header">
      <div class="container">
        <h3><%= link_to 'Samet Ali SAMETOĞLU', root_path %></h3>
        <ul>
            <li><%= link_to 'Markalar', brands_path %></li>
              <li><%= link_to 'Ürünüler', products_path %></li>
        </ul>
      </div>
    </div>

    <div id="content">
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product, local:true do |form|  %>


      <% if @product.errors.any? %>
        <div id="error_explanation">
          <div class="form-group alert alert-danger">
          <h2>
            <%= pluralize(@product.errors.count, "Hata") %> yakalandı:
          </h2>
          <ul>
            <% @product.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
          </div>
          </div>
      <% end %>

    <div class="form_body">
          <div class="form-group">
            <%= form.label :name ,class:"col-form-label col-form-label-lg"  %><br/>
            <%= form.text_field :name , class:"form-control form-control-lg" %>
          </div>
          <div class="form-group">
            <%= form.label :color ,class:"col-form-label col-form-label-lg"  %><br/>
            <%= form.text_field :color , class:"form-control form-control-lg" %>
          </div>
          <div class="form-group">
            <%= form.label :price ,class:"col-form-label col-form-label-lg"  %><br/>
            <%= form.text_field :price , class:"form-control form-control-lg" %>
          </div>
          <div class="form-group">
            <%= form.label :brand_id ,class:"col-form-label col-form-label-lg" %><br/>
            <%= form.collection_select :brand_id , Brand.order(:name), :id, :name, include_blank: true %>
          </div>
          <div class="form-group">
            <%= form.submit %>
          </div>
    <% end %>

app/views/products/_product.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Color</th>
      <th scope="col">Price</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
<% @brand.products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.color %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Delete', product_path(product),
            method: :delete,
            data: { confirm: 'Emin misin?' } %></td>

  </tr>
  </tbody>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h3>Edit product</h3>
</div>
<%= render 'products/form' %>

app/views/products/index.html.erb
<div class="col-lg-12">




  <div class="card" style="width: 100%;">

    <div class="card-body">
      <h5 class="card-title">Products List</h5>
        <p class="card-text"><%= link_to 'New Product', new_product_path,class:"page_new_button" %></p>
    </div>


  </div>

<table class="table">
  <thead  class="thead-dark">
  <tr>
    <th>ID</th>
    <th>İsim</th>
    <th>Renk</th>
    <th>Fiyat</th>
    <th>Marka</th>
  </tr>
</thead>
<tbody>
  <% @products.each do |product| %>
    <tr>
      <th><%= product.id %></th>
      <td><%= product.name %></td>
      <td><%= product.color %></td>
      <td><%= product.price %></td>
      <td><%= product.brand.name %></td>
    </tr>
  <% end %>
</tbody>

</table>
</div>

app/views/products/new.html.erb
<div class="col-lg-12 col-md-12">
    <h3 class="page_title">New Product</h3>
    <%= render 'form' %>
</div>

app/views/wellcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My e-ticaret', controller: 'brands' %>